smartphone_count=0;basicphone_count=0;tablet_count=0;internetservice_count=0;previous_count=0;var datasets=new Array;var dataset_rules={email:{day:{0:0,5:1,25:7,50:15,100:29,250:73},month:{0:0,150:1,750:7,1500:15,3000:29,7500:73}},web:{day:{0:0,5:150,25:750,50:1500,100:3000,250:7500},month:{0:0,150:150,750:750,1500:1500,3000:3000,7500:7500}},music:{day:{0:0,5:150,15:450,60:1800,120:3600},month:{0:0,150:150,450:450,1800:1800,3600:3600,}},video:{day:{0:0,2:650,10:3250,30:9750,60:19500},month:{0:0,150:150,450:450,1800:1800,3600:3600}}};$(document).ready(function(){setDropdowns();$('.plan-steps').click(function(){return false;});$('.start-calculate-btn').click(function(){calculateDataUsage();});});$('.dropdownLink').live("click",function(a){c=$(this).prev('ul.dropdownMenu');if(c.length>0){if($(this).prev('ul.dropdownMenu').css("display")=="none"){$("ul.dropdownMenu").hide();$(this).prev('ul.dropdownMenu').show();}else{$("ul.dropdownMenu").hide();$(this).prev('ul.dropdownMenu').hide();}}
return false;});$("ul.dropdownMenu li").live("click",function(a){a.preventDefault();var opt=$(this).parents('li').find('select option[value='+$(this).find('a').text()+']'),select=$(this).parents('li').find('select'),ul=$(this).parents('ul.dropdownMenu'),link=ul.next('a.dropdownLink');link.find('span').text($(this).find('a').text());$(this).parents('ul.dropdownMenu').find('a').removeClass('selected');$(this).find("a").addClass("selected");$(this).parents('li').find('select option').removeAttr('selected');opt.attr('selected','selected')
opt.trigger('click');opt.trigger('change');if(ul.attr('id')=='smartphone_countStyled'){smartphone_count=0;smartphone_count+=Number($(this).text());}
if(ul.attr('id')=='basicphone_countStyled'){basicphone_count=0;basicphone_count+=Number($(this).text());}
if(ul.attr('id')=='tablet_countStyled'){tablet_count=0;tablet_count+=Number($(this).text());}
if(ul.attr('id')=='internetservice_countStyled'){internetservice_count=0;internetservice_count+=Number($(this).text());}
showCalculateButton();$(this).parents('ul.dropdownMenu').hide();});$(document).click(function(){$('ul.dropdownMenu').hide();});function setDropdowns(){var dClass='dropdown',selects=$("select."+dClass),el_id,selected;selects.css({position:"absolute",left:"-9999px",top:"-9999px"});selects.each(function(i,el){el_id=$(el).attr('id');selected=($(el).find("option[selected=selected]").length>0)?$(el).find("option[selected=selected]"):$(el).find('option').first();selected_link=$(el).after('<a href="javascript:void(0)" class="dropdownLink" rel="'+el_id+'"><span>'+selected.text()+'</span></a>');ul_content='<ul class="dropdownMenu" id="'+el_id+'Styled" >';options=$(el).find('option');options.each(function(opt_index,opt){if(opt==selected)li_class='selected';else li_class='';li_text='<a href="javascript:void(0)" class="'+li_class+'">'+$(opt).text()+"</a>";ul_content+='<li>'+li_text+'</li>';});ul_content+='</ul>';ul=selected_link.after(ul_content);$('.dropdownMenu').hide();});}
function showCalculateButton(){if(smartphone_count||basicphone_count||tablet_count||internetservice_count){$('.start-calculate-btn').show();}else{$('.start-calculate-btn').hide();}}
function calculateDataUsage(){var total_count=smartphone_count+basicphone_count+tablet_count+internetservice_count;if(total_count>6){alert('Maximum number of devices exceeded. You can only have 6 devices.');}else{if((total_count>previous_count)||(total_count<previous_count)){$('ul.plan-steps li').removeClass('current');$('ul.plan-steps li').eq(1).addClass('current');$('.tab2').show();previous_count=total_count;populateDevices();}}}
function createDeviceFragment(type){var device=new Array;var type_name='';if(type=='smartphone')type_name='Smartphone';if(type=='basicphone')type_name='Basic Phone';if(type=='tablet')type_name='Tablet';if(type=='internetservice')type_name='Internet Service';device={id:create_uid(),type:type,type_name:type_name,data:{web:0,email:0,music:0,video:0}};return device;}
function populateDevices(){datasets=new Array;for(var i=0;i<smartphone_count;i++){device=createDeviceFragment("smartphone");datasets.push(device);}
for(var i=0;i<basicphone_count;i++){device=createDeviceFragment("basicphone");datasets.push(device);}
for(var i=0;i<tablet_count;i++){device=createDeviceFragment("tablet");datasets.push(device);}
for(var i=0;i<internetservice_count;i++){device=createDeviceFragment("internetservice");datasets.push(device);}
populateDeviceList('.tab2-list');}
function populateDeviceList(list_class){$(list_class).html('');var li='';var li_class='';for(var i=0;i<datasets.length;i++){li_class='';if(i==0){li_class='selected';}
li_class=li_class+' '+datasets[i]['type']+'_device';li+='<li class="'+li_class+'" id="'+datasets[i]['id']+'">';li+='<a href="#" class="close"></a>';li+='<div class="tab-img centerText">'
li+='<img src="images/'+datasets[i]['type']+'.png"/>';li+='</div>';li+='<div class="tab-title oswald cap centerText">'+datasets[i]['type_name'];li+='</div>';li+='</li>';}
$(list_class).html(li);}
function create_uid(){var A=new Date();var B=A.getFullYear()+""+A.getMonth()+""+A.getDate()+""+A.getTime();return B;}